// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import redirects from './src/redirects.json' with { type: 'json' };
import notesSidebar from './src/sidebar.json' with { type: 'json' };

// https://astro.build/config
export default defineConfig({
	// Cloudflare Workers static-assets URL (swap for a custom domain later).
	site: 'https://notesbyjoshua.joshuabie2010.workers.dev',
	// Pre-bundle the Supabase SDK so the dev server doesn't re-optimize it
	// mid-session (the cause of "504 Outdated Optimize Dep").
	vite: {
		optimizeDeps: { include: ['@supabase/supabase-js'] },
	},
	// Preserve old URLs from reorganized notes (generated by scripts/migrate_notes.py).
	redirects,
	markdown: {
		// MathJax-style `$...$` (inline) and `$$...$$` (display) delimiters, rendered with KaTeX.
		remarkPlugins: [remarkMath],
		// strict: false -> render quirks like an em-dash inside math instead of warning.
		rehypePlugins: [[rehypeKatex, { strict: false }]],
	},
	integrations: [
		starlight({
			title: 'Notes by Joshua',
			description: 'Math, Physics, and Thoughts',
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/notesbyjoshua' }],
			customCss: [
				// KaTeX stylesheet (math rendering).
				'katex/dist/katex.min.css',
				// Inter font + theorem boxes + note images, ported from the Jekyll site.
				'./src/styles/custom.css',
			],
			head: [
				{
					tag: 'link',
					attrs: { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
				},
				{
					tag: 'link',
					attrs: { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: true },
				},
				{
					tag: 'link',
					attrs: {
						rel: 'stylesheet',
						href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap',
					},
				},
			],
			sidebar: [
				{ label: 'Home', link: '/' },
				{ label: 'How to use these notes', link: '/how-to-use-these-notes/' },
				// Built from parent/nav_order by scripts/migrate_notes.py (src/sidebar.json),
				// so units group under their real course regardless of URL folder.
				{ label: 'Notes', items: notesSidebar },
				{ label: 'Practice Problems', link: '/practiceproblems/practice/' },
				{ label: 'Resources', link: '/resources/resources/' },
				{ label: 'Blog', link: '/blog/' },
				{ label: 'About', link: '/about/' },
				{ label: 'Feedback', link: '/feedback/' },
				{ label: 'My Dashboard', link: '/dashboard/' },
				{ label: 'Account', link: '/account/' },
			],
		}),
	],
});
